#include "Servo.h"

#include "stm32f3xx_hal.h"   /* TIM_HandleTypeDef, HAL_TIM_PWM_Start, __HAL_TIM_SET_COMPARE */

/* ===== TIM handles generated by CubeMX (defined in main.c) ===== */
extern TIM_HandleTypeDef htim2;   /* Arm servos */
extern TIM_HandleTypeDef htim3;   /* Gripper servo */

/* ===== Setpoints (public, declared in Servo.h) ===== */
volatile uint16_t servo1_count_us = SERVO_ARM_INIT_US;   /* Arm1 */
volatile uint16_t servo2_count_us = SERVO_ARM_INIT_US;   /* Arm2 */
volatile uint16_t servo3_count_us = SERVO_GRIP_0DEG_US;  /* Gripper */

/* ===== Mapping: change ONLY here if pins/timers change ===== */
#define ARM1_TIM   (&htim2)
#define ARM1_CH    TIM_CHANNEL_1

#define ARM2_TIM   (&htim2)
#define ARM2_CH    TIM_CHANNEL_2

#define GRIP_TIM   (&htim3)
#define GRIP_CH    TIM_CHANNEL_2

/* ===== Private helpers ===== */
static uint16_t clamp_u16(uint32_t v, uint16_t lo, uint16_t hi)
{
    if (v < (uint32_t)lo) return lo;
    if (v > (uint32_t)hi) return hi;
    return (uint16_t)v;
}

static void write_us(TIM_HandleTypeDef *htim, uint32_t channel, uint16_t pulse_us)
{
    /* Assumes timer tick is configured to 1us (PSC=71 @ 72MHz) */
    __HAL_TIM_SET_COMPARE(htim, channel, pulse_us);
}

static void apply_all_clamped(void)
{
    /* Arm servos: clamp 1000..2000us */
    write_us(ARM1_TIM, ARM1_CH, clamp_u16(servo1_count_us, SERVO_US_MIN, SERVO_US_MAX));
    write_us(ARM2_TIM, ARM2_CH, clamp_u16(servo2_count_us, SERVO_US_MIN, SERVO_US_MAX));

    /* Gripper: clamp to your limited range */
    write_us(GRIP_TIM, GRIP_CH, clamp_u16(servo3_count_us, SERVO_GRIP_0DEG_US, SERVO_GRIP_60DEG_US));
}

/* ===== Public API ===== */
void Servo_Init(void)
{
    /* Start PWM outputs (timers must already be initialized in main.c) */
    (void)HAL_TIM_PWM_Start(ARM1_TIM, ARM1_CH);
    (void)HAL_TIM_PWM_Start(ARM2_TIM, ARM2_CH);
    (void)HAL_TIM_PWM_Start(GRIP_TIM, GRIP_CH);

    /* Safe startup positions */
    servo1_count_us = SERVO_ARM_INIT_US;
    servo2_count_us = SERVO_ARM_INIT_US;
    servo3_count_us = SERVO_GRIP_0DEG_US;

    apply_all_clamped();
}

void Servo_Apply(void)
{
    apply_all_clamped();
}

/* ===== Optional convenience setters (keep main.c clean) ===== */
void Servo_SetArm1US(uint16_t us)
{
    servo1_count_us = us;
}

void Servo_SetArm2US(uint16_t us)
{
    servo2_count_us = us;
}

void Servo_SetGripperUS(uint16_t us)
{
    servo3_count_us = us;
}
